import breakfast01 from './img/menu/cheeses-with-sour-cream-and-cherry-jam.jpg';
import breakfast02 from './img/menu/omelet-like-grandmas.jpg';
import breakfast03 from './img/menu/ukrainian-soul.jpg';
import breakfast04 from './img/menu/oatmeal.jpg';
import breakfast05 from './img/menu/briosh-bun-with-jam.jpg';
import dumplings01 from './img/menu/dumplings-with-sour-cream.jpg';
import dumplings02 from './img/menu/dumplings-with-creamy-mushroom-sauce.jpg';
import dumplings03 from './img/menu/cheese-curd-with-salad.jpg';
import dumplings04 from './img/menu/derun-slender-nastya.jpg';
import dumplings05 from './img/menu/сarpathian-derunchiki.jpg';
import snack01 from './img/menu/cutting-from-the-tongue.jpg';
import snack02 from './img/menu/three-kinds-of-sandwiches.jpg';
import snack03 from './img/menu/three-ladies.jpg';
import snack04 from './img/menu/carp-strips.jpg';
import snack05 from './img/menu/something-with-something.jpg';
import snack06 from './img/menu/herring-with-a-shell.jpg';
import snack07 from './img/menu/cheese-plateau.jpg';
import snack08 from './img/menu/meat-plate.jpg';
import snack09 from './img/menu/assorted-pickles.jpg';
import snack10 from './img/menu/pate-with-currant-jam.jpg';
import first01 from './img/menu/ukrainian-borsch.jpg';
import first02 from './img/menu/bograch-carpathian.jpg';
import first03 from './img/menu/chicken-broth.jpg';
import salads01 from './img/menu/salads-with-chicken.jpg';
import salads02 from './img/menu/ceasar-salad-in-ukrainian.jpg';
import salads03 from './img/menu/ceasar-salad-with-shrimps.jpg';
import salads04 from './img/menu/salad-of-athens-in-guests.jpg';
import salads05 from './img/menu/salad-neighborhood-nerves.jpg';
import salads06 from './img/menu/salad-with-veal.jpg';
import salads07 from './img/menu/homemade-salad.jpg';
import dishes01 from './img/menu/ribs-with-prunes.jpg';
import dishes02 from './img/menu/kyiv-style-cotlet.jpg';
import dishes03 from './img/menu/cabbage-rolls.jpg';
import dishes04 from './img/menu/wings-in-mustard-honey-sauce.jpg';
import dishes05 from './img/menu/bloody-sausage.jpg';
import dishes06 from './img/menu/pan-from-the-bleak-sea.jpg';
import dishes07 from './img/menu/pork-in-the-pan.jpg';
import dishes08 from './img/menu/cossack-pan.jpg';
import dishes09 from './img/menu/banosh.jpg';
import dishes10 from './img/menu/river-carps.jpg';
import dishes11 from './img/menu/ulanivsky-potatoes.jpg';
import hosper01 from './img/menu/shashlyk-with-neck-pork.jpg';
import hosper02 from './img/menu/сhicken-barbecue.jpg';
import hosper03 from './img/menu/minced-mutton-chop-in-ukrainian.jpg';
import hosper04 from './img/menu/cropped-pork-sousage.jpg';
import hosper05 from './img/menu/chicken-sousages-with-smocked-lard.jpg';
import hosper06 from './img/menu/steering-wheel-with-chron.jpg';
import hosper07 from './img/menu/sreack-with-butter.jpg';
import hosper08 from './img/menu/ribeye-steak.jpg';
// import hosper08 from './img/menu/filet-mignon-with-vegetable-salsa.jpg';
import hosper09 from './img/menu/baked-mackerel-with-potatoes.jpg';
import hosper10 from './img/menu/lavash-with-chesse-and-smoked-lard.jpg';
import hosper11 from './img/menu/grilled-vegetables.jpg';
import hosper12 from './img/menu/meat-set1-otaman.jpg';
import hosper13 from './img/menu/meat-set-no-2-cossack.jpg';
import vareniks01 from './img/menu/vareniks-with-potatoes.jpg';
import vareniks02 from './img/menu/vareniks-with-cabbage-and-mushrooms.jpg';
import vareniks03 from './img/menu/vareniks-with-salted-cheese.jpg';
import vareniks04 from './img/menu/vareniks-with-meat.jpg';
import tableImg from './img/tables/table.jpg';

export const initialValue = {
    isLoading: false,
    list: [
        { 
            id: 1,
            type: 'breakfast',
            title: 'СИРНИКИ ЗІ СМЕТАНОЮ ТА ВИШНЕВИМ КОНФІТЮРОМ',
            weight: 320,
            rate: 5,
            img: breakfast01,
            price: 95,
        },
        {
            id: 2,
            type: 'breakfast',
            title: 'ОМЛЕТ ЯК В БАБУСІ',
            weight: 330,
            rate: 4,
            img: breakfast02,
            price: 140,
            composition: 'Яйця, печериці, сир фета, овочі, ковбаса домашня',
        },
        {
            id: 3,
            type: 'breakfast',
            title: 'УКРАЇНСЬКА ДУША',
            weight: 330,
            rate: 4,
            img: breakfast03,
            price: 130,
            composition: 'Яйця, салатка, ковбаски мисливські, картопляні кульки, крутони',
        },
        {
            id: 4,
            type: 'breakfast',
            title: 'ВІВСЯНКА',
            weight: 360,
            rate: 4,
            img: breakfast04,
            price: 90,
            composition: 'Вівсянка варена на молоці, курага, сезонні ягоди',
        },
        {
            id: 5,
            type: 'breakfast',
            title: 'БУЛОЧКА "БРІОШ" З ДЖЕМОМ',
            weight: 360,
            rate: 4,
            img: breakfast05,
            price: 90,
            composition: 'Булочка власного виробництва, вершкове масло, яблучно-грушеве варення, смородиновий джем',
        },        
        {
            id: 6,
            type: 'potato_pancake',
            title: 'КЛАСИЧНІ ДЕРУНИ ЗІ СМЕТАНКОЮ',
            weight: 250,
            rate: 4,
            img: dumplings01,
            price: 90,
        },        
        {
            id: 7,
            type: 'potato_pancake',
            title: 'ДЕРУН З ВЕРШКОВО-ГРИБНИМ СОУСОМ',
            weight: 340,
            rate: 4,
            img: dumplings02,
            price: 120,
        },        
        {
            id: 8,
            type: 'potato_pancake',
            title: 'ДЕРУН СИРНИЙ З САЛАТКОЮ',
            weight: 330,
            rate: 4,
            img: dumplings03,
            price: 110,
            composition: 'Сир сулугуні, салатка з помідорками чері',
        },        
        {
            id: 9,
            type: 'potato_pancake',
            title: 'ДЕРУН СИРНИЙ З САЛАТКОЮ',
            weight: 330,
            rate: 4,
            img: dumplings03,
            price: 110,
            composition: 'Сир сулугуні, салатка з помідорками чері',
        },        
        {
            id: 10,
            type: 'potato_pancake',
            title: 'ДЕРУН СТРУНКА НАСТЯ',
            weight: 360,
            rate: 4,
            img: dumplings04,
            price: 160,
            composition: 'З лососем і крем-сиром',
        },        
        {
            id: 11,
            type: 'potato_pancake',
            title: 'КАРПАТСЬКІ ДЕРУНЧИКИ',
            weight: 400,
            rate: 4,
            img: dumplings05,
            price: 150,
            composition: 'Гуляш в солодкому соусі з томатів',
        },        
        {
            id: 12,
            type: 'snack',
            title: 'НАРІЗКА З ЯЗИКА',
            weight: 260,
            rate: 4,
            img: snack01,
            price: 285,
            composition: 'охолоджений яловичий маринований язик, хрустка рукола, вишневий бальзамік',
        },        
        {
            id: 13,
            type: 'snack',
            title: 'КАНАПКИ ТРИ СОРТИ',
            weight: 410,
            rate: 4,
            img: snack02,
            price: 160,
            composition: 'В\'ялені томати, морква по-корейськи, буженина, маринований перець, масло, тюлька',
        },        
        {
            id: 14,
            type: 'snack',
            title: 'ТРИ ПАНЬКИ',
            weight: 330,
            rate: 4,
            img: snack03,
            price: 155,
            composition: 'Сало печене, сало мелене з часничком, свійська підчеревина, хліб, хрін, гірчиця',
        },        
        {
            id: 15,
            type: 'snack',
            title: 'СТРІПСИ З КОРОПА',
            weight: 140/50,
            rate: 4,
            img: snack04,
            price: 160,
            composition: 'філе коропа в хрусткій паніровці з соусом «Тартар»',
        },        
        {
            id: 16,
            type: 'snack',
            title: 'ШОСЬ З ЧИМОСЬ',
            weight: 150/50,
            rate: 4,
            img: snack05,
            price: 180,
            composition: 'Сир брі в паніровці панко з джемом зі смородини',
        },        
        {
            id: 17,
            type: 'snack',
            title: 'ОСЕЛЕДЕЦЬ З ТЮЛЬОЧКОЮ',
            weight: 270,
            rate: 4,
            img: snack06,
            price: 145,
            composition: 'Картопля печена, цибулька маринована',
        },        
        {
            id: 18,
            type: 'snack',
            title: 'СИРНЕ ПЛАТО',
            weight: 250,
            rate: 4,
            img: snack07,
            price: 160,
            composition: 'Тарілка локальних сирів, мед, грецькі горіхи, сухофрукти',
        },
        {
            id: 19,
            type: 'snack',
            title: 'М\'ЯСНА ТАРІЛЬ',
            weight: 230,
            rate: 4,
            img: snack08,
            price: 170,
            composition: 'Буженина, печене сало, ковбаса домашня, хрін',
        },
        {
            id: 20,
            type: 'snack',
            title: 'АСОРТІ СОЛІНЬ',
            weight: 350,
            rate: 4,
            img: snack09,
            price: 110,
            composition: 'Томати, огірочки, часник, капуста',
        },
        {
            id: 21,
            type: 'snack',
            title: 'ПАШТЕТ ІЗ ДЖЕМОМ СМОРОДИНИ',
            weight: 280,
            rate: 4,
            img: snack10,
            price: 120,
            composition: 'паштет з курячої печінки, джем зі смородини, пампушка власного виробництва',
        },
        {
            id: 22,
            type: 'first-courses',
            title: 'БОРЩ УКРАЇНСЬКИЙ',
            weight: 350,
            rate: 4,
            img: first01,
            price: 110,
            composition: 'Ребра, підчеревина, сметана, цибуля',
        },
        {
            id: 23,
            type: 'first-courses',
            title: 'БОГРАЧ КАРПАТСЬКИЙ',
            weight: 350,
            rate: 4,
            img: first02,
            price: 120,
            composition: 'Свинина, телятина, зелень',
        },
        {
            id: 24,
            type: 'first-courses',
            title: 'КУРЯЧИЙ БУЛЬЙОН',
            weight: 350,
            rate: 4,
            img: first03,
            price: 95,
            composition: 'Куряче філе, локшина, зелень',
        },
        {
            id: 25,
            type: 'salads',
            title: 'САЛАТ З КУРКОЮ',
            weight: 330,
            rate: 4,
            img: salads01,
            price: 190,
            composition: 'vікс салату, філе куряче, перець болгарський, томати, кабачок, огірки, соус "Теріякі", кунжут, цибуля синя',
        },
        {
            id: 26,
            type: 'salads',
            title: 'САЛАТ ЦЕЗАР ПО-УКРАЇНСЬКИ',
            weight: 330,
            rate: 4,
            img: salads02,
            price: 180,
            composition: 'мікс салату, філе куряче, чері, яйця перепелині, соус "Цезар", бекон, грінки, пармезан',
        },
        {
            id: 27,
            type: 'salads',
            title: 'САЛАТ ЦЕЗАР З КРЕВЕТКАМИ',
            weight: 260,
            rate: 4,
            img: salads03,
            price: 230,
            composition: 'мікс салату, креветки, чері, яйця перепелині, соус "Цезар", грінки, пармезан, перець чилі',
        },
        {
            id: 28,
            type: 'salads',
            title: 'САЛАТ АФІНИ В ГОСТЯХ',
            weight: 320,
            rate: 4,
            img: salads04,
            price: 155,
            composition: 'мікс салату, фета, дресінг грецький, томати, оливки, перець болгарський, огірки, цибуля синя',
        },
        {
            id: 29,
            type: 'salads',
            title: 'САЛАТ СУСІДСЬКІ НЕРВИ',
            weight: 140,
            rate: 4,
            img: salads05,
            price: 160,
            composition: 'мікс салату, печінка куряча, вершки, мед, чері, перець чилі',
        },
        {
            id: 30,
            type: 'salads',
            title: 'САЛАТ З ТЕЛЯТИНОЮ',
            weight: 310,
            rate: 4,
            img: salads06,
            price: 220,
            composition: 'мікс салату, телятина, чері, в\'ялені томати, вишневий бальзамік, мигдальні пластівці',
        },
        {
            id: 31,
            type: 'salads',
            title: 'САЛАТ ДОМАШНІЙ',
            weight: 270,
            rate: 4,
            img: salads07,
            price: 90,
            composition: 'капуста білокачанна, огірки, зелень',
        },
        {
            id: 32,
            type: 'main',
            title: 'РЕБРА З ЧОРНОСЛИВОМ',
            weight: 480,
            rate: 4,
            img: dishes01,
            price: 240,
            composition: 'Картопля печена з пармезаном, тушковані овочі',
        },
        {
            id: 33,
            type: 'main',
            title: 'КОТЛЕТА ПО-КИЇВСЬКИ',
            weight: 240/130,
            rate: 4,
            img: dishes02,
            price: 155,
            composition: 'Ніжне картопляне пюре з класичною котлетою по-київськи',
        },
        {
            id: 34,
            type: 'main',
            title: 'ГОЛУБЧИКИ',
            weight: 300/30/120,
            rate: 4,
            img: dishes03,
            price: 160,
            composition: 'Улюблені голубці з вершково-грибним соусом',
        },
        {
            id: 35,
            type: 'main',
            title: 'КРИЛА В ГІРЧИЧНО-МЕДОВОМУ СОУСІ',
            weight: 500/80,
            rate: 4,
            img: dishes04,
            price: 220,
            composition: 'Печериці, чері, червона цибулька',
        },
        {
            id: 36,
            type: 'main',
            title: 'КРОВ\'ЯНКА',
            weight: 220,
            rate: 4,
            img: dishes05,
            price: 135,
            composition: 'Як з бабусиної печі. Скуштувавши цю кров\'янку, поринете у дитячі спогади.',
        },
        {
            id: 37,
            type: 'main',
            title: 'ПАТЕЛЬНЯ З ЧОРНОГО МОРЯ',
            weight: 420,
            rate: 4,
            img: dishes06,
            price: 255,
            composition: 'Креветки, цибуля, чері, картопля, болгарський перець',
        },
        {
            id: 38,
            type: 'main',
            title: 'СВІЖИНА НА ПАТЕЛЬНІ',
            weight: 400,
            rate: 4,
            img: dishes07,
            price: 220,
            composition: 'Ошийок, свинна печінка, цибулька',
        },
        {
            id: 39,
            type: 'main',
            title: 'ПАТЕЛЬНЯ КОЗАЦЬКА',
            weight: 450,
            rate: 4,
            img: dishes08,
            price: 220,
            composition: 'Цибулька, яловичина, бекон, картопля, квашені огірочки',
        },
        {
            id: 40,
            type: 'main',
            title: 'БАНОШ',
            weight: 250,
            rate: 4,
            img: dishes09,
            price: 90,
            composition: 'шкварки, бринза, вершки',
        },
        {
            id: 41,
            type: 'main',
            title: 'КАРАСІ РІЧКОВІ',
            weight: 270,
            rate: 4,
            img: dishes10,
            price: 125,
            composition: 'Обсмажені в кукурудзяному борошні',
        },
        {
            id: 42,
            type: 'main',
            title: 'КАРТОПЛЯ ПО-УЛАНІВСЬКИ',
            weight: 200,
            rate: 4,
            img: dishes11,
            price: 70,
            composition: 'часничок, зелень',
        },
        {
            id: 43,
            type: 'hosper',
            title: 'ШАШЛИК З ОШИЙКА (СВИНИНА)',
            weight: 100,
            rate: 4,
            img: hosper01,
            price: 70,
            composition: 'Мариноване м\'ясо з цибулькою та ароматними спеціями.',
        },
        {
            id: 44,
            type: 'hosper',
            title: 'ШАШЛИК ІЗ КУРКИ',
            weight: 100,
            rate: 4,
            img: hosper02,
            price: 60,
        },
        {
            id: 45,
            type: 'hosper',
            title: 'ЛЮЛЯ ПО-УКРАЇНСЬКИ',
            weight: 100,
            rate: 4,
            img: hosper03,
            price: 60,
        },
        {
            id: 46,
            type: 'hosper',
            title: 'КОВБАСА СВИННА РУБЛЕНА',
            weight: 100,
            rate: 4,
            img: hosper04,
            price: 60,
        },
        {
            id: 47,
            type: 'hosper',
            title: 'КОВБАСА СВИННА РУБЛЕНА',
            weight: 100,
            rate: 4,
            img: hosper05,
            price: 60,
        },
        {
            id: 48,
            type: 'hosper',
            title: 'РУЛЬКА З ХРОНОМ',
            weight: 100,
            rate: 4,
            img: hosper06,
            price: 65,
        },
        {
            id: 49,
            type: 'hosper',
            title: 'СТЕЙК З МАСЛЯНОЇ',
            weight: 100,
            rate: 4,
            img: hosper07,
            price: 95,
        },
        {
            id: 50,
            type: 'hosper',
            title: 'СТЕЙК РІБАЙ',
            weight: 100,
            rate: 4,
            img: hosper08,
            price: 85,
        },
        {
            id: 51,
            type: 'hosper',
            title: 'ФІЛЕ МІНЬЙОН З ОВОЧЕВОЮ САЛЬСОЮ',
            weight: 300/100,
            rate: 4,
            img: hosper09,
            price: 200,
        },
        {
            id: 52,
            type: 'hosper',
            title: 'ЛАВАШ З СИРОМ ТА КОПЧЕНИМ САЛОМ',
            weight: 270,
            rate: 4,
            img: hosper10,
            price: 115,
        },
        {
            id: 53,
            type: 'hosper',
            title: 'ОВОЧІ ГРИЛЬ',
            weight: 200,
            rate: 4,
            img: hosper11,
            price: 110,
        },
        {
            id: 54,
            type: 'hosper',
            title: 'СЕТ М\'ЯСНИЙ №1 "ОТАМАН"',
            weight: 930,
            rate: 4,
            img: hosper12,
            price: 645,
            composition: 'Шашлик з ошийка (свинина), шашлик із курки, ребра з сливовим соусом, крила в соусі з чорносливу, ковбаски свинні з сулугуні, ковбаски курячі з копченим салом, лаваш, аджика, кетчуп із слив, хрін з бузиною',
        },
        {
            id: 55,
            type: 'hosper',
            title: 'СЕТ М\'ЯСНИЙ №2 "КОЗАЦЬКИЙ"',
            weight: 2200,
            rate: 4,
            img: hosper13,
            price: 1295,
            composition: 'Козакам та козачкам "Гетьман" у подарунок. Шашлик з ошийка (свинина), шашлик із курки, ребра з сливовим соусом, крила в соусі з чорносливу, ковбаски свинні з сулугуні, ковбаски курячі з копченим салом, лаваш, аджика, кетчуп із слив, хрін з бузиною, соління українські',
        },
        {
            id: 56,
            type: 'vareniks',
            title: 'ВАРЕНИКИ З КАРТОПЛЕЮ',
            weight: 2200,
            rate: 4,
            img: vareniks01,
            price: 1295,
            composition: 'З шкварками та сметаною',
        },
        {
            id: 57,
            type: 'vareniks',
            title: 'ВАРЕНИКИ З КАПУСТОЮ ТА ГРИБАМИ',
            weight: 230/50,
            rate: 4,
            img: vareniks02,
            price: 95,
            composition: 'З сметаною та цибулькою',
        },
        {
            id: 58,
            type: 'vareniks',
            title: 'ВАРЕНИКИ З СОЛОНИМ СИРОМ',
            weight: 230/50,
            rate: 4,
            img: vareniks03,
            price: 110,
            composition: 'З шкварками та сметаною',
        },
        {
            id: 59,
            type: 'vareniks',
            title: 'ВАРЕНИКИ З М\'ЯСОМ',
            weight: 230/50,
            rate: 4,
            img: vareniks04,
            price: 130,
            composition: 'З сметаною та цибулькою',
        },
    ],
    orders: [],
    tables: [
        {
            id: 1,
            name: 'table 1',
            img: tableImg,
        },
        {
            id: 2,
            name: 'table 2',
            img: tableImg,
        },
        {
            id: 3,
            name: 'table 3',
            img: tableImg,
        },
        {
            id: 4,
            name: 'table 4',
            img: tableImg,
        },
        {
            id: 5,
            name: 'table 5',
            img: tableImg,
        },
        {
            id: 6,
            name: 'table 6',
            img: tableImg,
        },
    ],
    personnel: [
        {
            id: 1,
            name: 'Анатолій',
        },
        {
            id: 2,
            name: 'Олесандр',
        },
        {
            id: 3,
            name: 'Сергій',
        },
        {
            id: 4,
            name: 'Зіна',
        },
        {
            id: 5,
            name: 'Ольга',
        },
        {
            id: 6,
            name: 'Яна',
        },
    ]
}
